name: Expo Publish

on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.15'
    - name: Install Dependencies
      run: npm install
    - name: Publish to Expo
      env:
        EXPO_TOKEN: EAaSLhdeBRvAyDlIiRfpXBvADzAh7wBbLdIq9W7E
      run: npx expo publish --non-interactive --token $EXPO_TOKEN
