name: Expo Publish

on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.15' # Or your specific Node.js version
    - name: Install Dependencies
      run: npm install
    - name: Build Files
      run: npm build
      

